<?php

/**
 * Implements hook_form_FORM_ID_alter() for node_type_form.
 */
function fawesome_node_form_node_type_form_alter(&$form, &$form_state) {
  $type = $form['#node_type'];
  $form['name']['#weight'] = -10;
  $form['type']['#weight'] = -10;
  $form['description']['#weight'] = -5;
  $form['fawesome'] = array(
    '#title' => t('Icon'),
    '#type' => 'fawesome_select',
    '#weight' => -10,
    '#default_value' => variable_get('fawesome_' . $type->type, ''),
  );
}

/**
 * Implements hook_menu_link_alter().
 */
function fawesome_node_menu_link_alter(&$item) {
  foreach(node_type_get_types() as $type => $data){
    if($item['link_path'] == 'node/add/' . str_replace('_','-',$type) && $icon = variable_get('fawesome_' . $type)){
      $item['options']['fawesome'] = $icon;
    }
  }
}
